name: '[xprint] Check'

on:
  push:
    branches:
      - '**'

jobs:

  check:
    name: Check
    strategy:
      matrix:
        os:
          - windows-latest
          - macos-latest
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v4
      - name: Checkout
        uses: fewensa/actions/clone-dyn@new-clone-action
        with:
          repository: prtmax/xprint
          token: '${{ secrets.GH_TOKEN_0XFE10 }}'
          ref_file: .github/ref.txt

      - name: Setup Flutter SDK
        uses: flutter-actions/setup-flutter@v3
        with:
          channel: stable
          #version: 3.24.4

      - name: Setup Rust
        uses: actions-rust-lang/setup-rust-toolchain@v1
        with:
          toolchain: stable

      - name: Test deps
        run: |
          rustc --version
          cargo --version
          flutter --version

      - name: Setup git credential
        run: |
          git config --global credential.helper store
          echo 'https://${{ secrets.GITLAB_TOKEN }}@gitlab.com' > ~/.git-credentials

      - name: Check xprint
        working-directory: xprint/rust
        run: cargo b --release

      - name: Check bxprint_flutter
        working-directory: wrapper/bxprint_flutter/example
        if: matrix.os == 'windows-latest'
        run: |
          flutter pub get
          flutter build windows

      - name: Check bxprint_flutter
        working-directory: wrapper/bxprint_flutter/example
        if: matrix.os == 'macos-latest'
        run: |
          flutter pub get
          flutter build macos

  notify:
    name: Notify failure
    runs-on: ubuntu-latest
    needs:
      - check
    if: ${{ always() && contains(needs.*.result, 'failure') }}
    steps:
      - uses: actions/checkout@v2
      - name: Checkout
        uses: fewensa/actions/clone-any@main
        with:
          platform: gitlab
          repository: prtmax/xprint
          access_token: '${{ secrets.GITLAB_TOKEN }}'
          ref_file: .github/ref.txt

      - uses: fewensa/actions/tepusher@main
        with:
          template: .maintain/notify/check-failed.md
          token: ${{ secrets.WEPLUSBOT_TOKEN }}
          receiver: "#d8bb7fbacf0849f1bb7fcc89a878a1a0"
