name: '[endfather] Check'

on:
  push:
    branches:
      - '**'

jobs:
  check-app-java:
    name: Check app java
    runs-on: ubuntu-latest
    strategy:
      matrix:
        package:
          - babosa
    steps:
      - uses: actions/checkout@v6
      - name: Setup Maven Action
        uses: s4u/setup-maven-action@v1.19.0
        with:
          java-version: 17
          maven-version: 3.9.11
          checkout-enabled: false
      - name: Checkout
        uses: repotea-workspace/kangumi/github-actions/clone-dyn@main
        with:
          repository: prtmax/endfather
          token: '${{ secrets.GH_TOKEN_0XFE10 }}'
          ref_file: .github/ref.txt


      - name: Check ${{ matrix.package }}
        working-directory: ${{ matrix.package }}
        run: mvn clean package -Dmaven.test.skip=true

      - uses: repotea-workspace/kangumi/github-actions/tepusher@main
        if: failure()
        with:
          template: .maintain/notify/check-failed.md
          token: ${{ secrets.WEPLUSBOT_TOKEN }}
          receiver: "#d8bb7fbacf0849f1bb7fcc89a878a1a0"
          aters: C1776236406
          vars: |
            app: babosa

  check-app-node:
    name: Check app node
    runs-on: ubuntu-latest
    strategy:
      matrix:
        package:
          - woodii
    steps:
      - uses: actions/checkout@v6
      - name: Checkout
        uses: repotea-workspace/kangumi/github-actions/clone-dyn@main
        with:
          repository: prtmax/endfather
          token: '${{ secrets.GH_TOKEN_0XFE10 }}'
          ref_file: .github/ref.txt

      - uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Check ${{ matrix.package }}
        run: |
          export NODE_OPTIONS=--max-old-space-size=4096
          cd ${{ matrix.package }}
          yarn install
          yarn build:stg

      - uses: repotea-workspace/kangumi/github-actions/tepusher@main
        if: failure()
        with:
          template: .maintain/notify/check-failed.md
          token: ${{ secrets.WEPLUSBOT_TOKEN }}
          receiver: "#d8bb7fbacf0849f1bb7fcc89a878a1a0"
          aters: C1776236406
          vars: |
            app: ${{ matrix.package }}
