name: '[labeldesktop] Check'

on:
  push:
    branches:
      - '**'

jobs:

  check:
    name: Check
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v2
      - name: Checkout
        uses: fewensa/actions/clone-any@main
        with:
          platform: gitlab
          repository: prtmax/labeldesktop
          access_token: '${{ secrets.GITLAB_TOKEN }}'
          ref_file: .github/ref.txt

      - name: Setup Flutter SDK
        uses: flutter-actions/setup-flutter@v3
        with:
          channel: stable
          version: 3.19.6

      - run: flutter --version

      - name: Setup git credential
        run: |
          git config --global credential.helper store
          echo 'https://${{ secrets.GITLAB_TOKEN }}@gitlab.com' > ~/.git-credentials

      - name: Install deps
        run: |
          flutter pub global activate get_cli
          flutter pub upgrade
          get generate locales assets/locales

      - name: Check build
        run: |
          flutter build windows

      - name: Compile Installer
        uses: Minionguyjpro/Inno-Setup-Action@v1.2.4
        with:
          path: labeldesktop.iss
          options: /O+

  notify:
    name: Notify failure
    runs-on: ubuntu-latest
    needs:
      - check
    if: ${{ always() && contains(needs.*.result, 'failure') }}
    steps:
      - uses: actions/checkout@v2
      - name: Checkout
        uses: fewensa/actions/clone-any@main
        with:
          platform: gitlab
          repository: prtmax/labeldesktop
          access_token: '${{ secrets.GITLAB_TOKEN }}'
          ref_file: .github/ref.txt

      - uses: fewensa/actions/tepusher@main
        with:
          template: .maintain/notify/check-failed.md
          token: ${{ secrets.WEPLUSBOT_TOKEN }}
          receiver: 66bc2051e4b0e36f485a957b
          aters: wxid_ntwefy6w95622,wxid_5634706356812,wxid_ny8c0ty1bz2o22

