name: 'Check'

on:
  push:
    branches:
      - '**'

jobs:
  trigger:
    name: Trigger
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: fewensa/actions/dyn-actions@migrate-to-github
        name: dyn-actions
        with:
          project_name: endfather
          ssh_key: ${{ secrets.GH_SSH_PRIVATE_KEY_0XFE10 }}


