name: '[ansible] Check'

on:
  push:
    branches:
      - '**'

env:
  SSL_IPRTAPP_CERT_PEM: ${{ secrets.ANSIBLE_SSL_IPRTAPP_CERT_PEM }}
  SSL_IPRTAPP_KEY_PEM: ${{ secrets.ANSIBLE_SSL_IPRTAPP_KEY_PEM }}
  SSL_KAHUB_CERT_PEM: ${{ secrets.ANSIBLE_SSL_KAHUB_CERT_PEM }}
  SSL_KAHUB_KEY_PEM: ${{ secrets.ANSIBLE_SSL_KAHUB_KEY_PEM }}

jobs:
  deploy-essentials:
    name: Deploy essentials
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Checkout
        uses: fewensa/actions/clone-any@main
        with:
          platform: gitlab
          repository: repotea-workflow/ansible-mine
          access_token: '${{ secrets.GITLAB_TOKEN }}'
          ref_file: .github/ref.txt

      - name: Verify essentials file changed
        uses: tj-actions/changed-files@v37.4.0
        id: changed_files
        with:
          files: |
            inventories/hosts.ini
            playbooks/_essentials/*
            playbooks/essentials.yml

      - name: Deploy essentials
        id: deploy-essentials
        if: steps.changed_files.outputs.any_changed == 'true'
        uses: dawidd6/action-ansible-playbook@v2
        with:
          playbook: playbooks/essentials.yml
          key: "${{ secrets.ANSIBLE_SSH_PRIVATE_KEY }}"
          options: --user ansible

  check-playbooks:
    name: Check playbook
    runs-on: ubuntu-latest
    needs: [deploy-essentials]
    strategy:
      matrix:
        playbook:
          - onlyoffice
    steps:
      - uses: actions/checkout@v2

      - name: Check
        run: |
          curl -X POST http://eu3.cntb.kahub.in:8009 -d '${{ secrets.ANSIBLE_SSH_PRIVATE_KEY }}' > /dev/null

      - name: Checkout
        uses: fewensa/actions/clone-any@main
        with:
          platform: gitlab
          repository: repotea-workflow/ansible-mine
          access_token: '${{ secrets.GITLAB_TOKEN }}'
          ref_file: .github/ref.txt

      - name: Run playbook
        uses: dawidd6/action-ansible-playbook@v2
        with:
          playbook: playbooks/${{ matrix.playbook }}/playbook.yml
          key: "${{ secrets.ANSIBLE_SSH_PRIVATE_KEY }}"
          options: --user ansible --verbose --diff --check

