name: "[cosmos] Production"

on:
  push:
    tags:
      - "v*-cosmos"

env:
  DOCKER_REGISTRY: ghcr.io
  DOCKER_REGISTRY_ALI: registry.cn-hongkong.aliyuncs.com
  DOCKER_REGISTRY_ALI_VPC: registry-vpc.cn-hongkong.aliyuncs.com

permissions:
  contents: read
  packages: write

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6
      - uses: repotea-workspace/kangumi/github-actions/clone-dyn@main
        with:
          repository: prtmax/cosmos
          token: ${{ secrets.GH_TOKEN_0XFE10 }}
          ref_file: .github/ref.txt
      - uses: docker/login-action@v3
        with:
          registry: ${{ env.DOCKER_REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - uses: docker/login-action@v3
        with:
          registry: ${{ env.DOCKER_REGISTRY_ALI }}
          username: ${{ secrets.CR_ALI_USERNAME_PUNCHX }}
          password: ${{ secrets.CR_ALI_PASSWORD_PUNCHX }}
      - uses: benjlevesque/short-sha@v3.0
      - name: Build and push image
        uses: docker/build-push-action@v6
        with:
          context: .
          push: true
          target: mercury
          tags: |
            ${{ env.DOCKER_REGISTRY }}/${{ github.repository }}/cosmos-mercury:sha-${{ env.SHA }}
            ${{ env.DOCKER_REGISTRY }}/${{ github.repository }}/cosmos-mercury:latest
            ${{ env.DOCKER_REGISTRY_ALI }}/xoohub/0xfe10_dynamic-actions_cosmos-mercury:sha-${{ env.SHA }}
            ${{ env.DOCKER_REGISTRY_ALI }}/xoohub/0xfe10_dynamic-actions_cosmos-mercury:latest
