name: "[byteone] Production"

on:
  push:
    tags:
      - "v*-byteone"
env:
  DOCKER_REGISTRY: ghcr.io
  DOCKER_REGISTRY_ALI: crpi-uhy920dintikwpn3.cn-shenzhen.personal.cr.aliyuncs.com
  DOCKER_REGISTRY_ALI_VPC: crpi-uhy920dintikwpn3-vpc.cn-shenzhen.personal.cr.aliyuncs.com
  BYTEONE_PROTECTED_BINARY_PROTECTION: garble

jobs:
  build-apps:
    name: Build
    runs-on: ubuntu-latest
    strategy:
      matrix:
        package:
          - name: core
            context: .
          - name: front
            context: pkgs/front
    steps:
      - uses: actions/checkout@v6
      - name: Checkout
        uses: repotea-workspace/kangumi/github-actions/clone-dyn@main
        with:
          repository: prtmax/byteone
          token: "${{ secrets.GH_TOKEN_0XFE10 }}"
          ref_file: .github/ref.txt
          submodules: recursive

      - name: Check
        working-directory: pkgs/${{ matrix.package.name }}
        run: |
          ls -la

      - name: Docker login
        uses: docker/login-action@v3
        with:
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
          registry: ${{ env.DOCKER_REGISTRY }}

      - name: Docker login (Aliyun)
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.CR_ALI_USERNAME_JOECHOW }}
          password: ${{ secrets.CR_ALI_PASSWORD_JOECHOW }}
          registry: ${{ env.DOCKER_REGISTRY_ALI }}

      - uses: benjlevesque/short-sha@v3.0

      - name: Set repo name
        run: echo "REPO_NAME=${GITHUB_REPOSITORY//\//_}" >> $GITHUB_ENV

      - name: Set image tags
        id: tags
        run: |
          echo "ghcr_sha=${{ env.DOCKER_REGISTRY }}/${{ github.repository }}/byteone-${{ matrix.package.name }}:sha-${{ env.SHA }}" >> $GITHUB_OUTPUT
          echo "ghcr_latest=${{ env.DOCKER_REGISTRY }}/${{ github.repository }}/byteone-${{ matrix.package.name }}:latest" >> $GITHUB_OUTPUT
          echo "ali_sha=${{ env.DOCKER_REGISTRY_ALI }}/coohub/${{ env.REPO_NAME }}_byteone-${{ matrix.package.name }}:sha-${{ env.SHA }}" >> $GITHUB_OUTPUT
          echo "ali_latest=${{ env.DOCKER_REGISTRY_ALI }}/coohub/${{ env.REPO_NAME }}_byteone-${{ matrix.package.name }}:latest" >> $GITHUB_OUTPUT

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Build and push docker image
        uses: docker/build-push-action@v6
        with:
          push: true
          context: ${{ matrix.package.context }}
          file: pkgs/${{ matrix.package.name }}/Dockerfile
          platforms: linux/amd64
          build-args: |
            ${{ matrix.package.args || '' }}
          tags: |
            ${{ steps.tags.outputs.ghcr_sha }}
            ${{ steps.tags.outputs.ghcr_latest }}
            ${{ steps.tags.outputs.ali_sha }}
            ${{ steps.tags.outputs.ali_latest }}

  build-release-apps:
    name: Build Release
    runs-on: ubuntu-latest
    continue-on-error: true
    strategy:
      matrix:
        package:
          - name: core
            context: .
          - name: front
            context: pkgs/front
    steps:
      - uses: actions/checkout@v6
      - name: Checkout
        uses: repotea-workspace/kangumi/github-actions/clone-dyn@main
        with:
          repository: prtmax/byteone
          token: "${{ secrets.GH_TOKEN_0XFE10 }}"
          ref_file: .github/ref.txt
          submodules: recursive

      - name: Check
        working-directory: pkgs/${{ matrix.package.name }}
        run: |
          ls -la

      - name: Docker login (Aliyun)
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.CR_ALI_USERNAME_JOECHOW }}
          password: ${{ secrets.CR_ALI_PASSWORD_JOECHOW }}
          registry: ${{ env.DOCKER_REGISTRY_ALI }}

      - uses: benjlevesque/short-sha@v3.0

      - name: Set repo name
        run: echo "REPO_NAME=${GITHUB_REPOSITORY//\//_}" >> $GITHUB_ENV

      - name: Set image tags
        id: tags
        run: |
          echo "release_sha=${{ env.DOCKER_REGISTRY_ALI }}/coohub/${{ env.REPO_NAME }}_byteone-${{ matrix.package.name }}-release:sha-${{ env.SHA }}" >> $GITHUB_OUTPUT
          echo "release_latest=${{ env.DOCKER_REGISTRY_ALI }}/coohub/${{ env.REPO_NAME }}_byteone-${{ matrix.package.name }}-release:latest" >> $GITHUB_OUTPUT

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Build release docker image
        uses: docker/build-push-action@v6
        with:
          push: true
          context: ${{ matrix.package.context }}
          file: pkgs/${{ matrix.package.name }}/Dockerfile
          platforms: linux/amd64
          build-args: |
            BYTEONE_BINARY_PROTECTION=${{ env.BYTEONE_PROTECTED_BINARY_PROTECTION }}
            ${{ matrix.package.args || '' }}
          tags: |
            ${{ steps.tags.outputs.release_sha }}
            ${{ steps.tags.outputs.release_latest }}

  deploy-apps:
    name: Deploy Apps
    runs-on: ubuntu-latest
    needs:
      - build-apps
    steps:
      - uses: actions/checkout@v6
      - name: Checkout
        uses: repotea-workspace/kangumi/github-actions/clone-dyn@main
        with:
          repository: prtmax/byteone
          token: "${{ secrets.GH_TOKEN_0XFE10 }}"
          ref_file: .github/ref.txt

      - name: Set repo name
        run: echo "REPO_NAME=${GITHUB_REPOSITORY//\//_}" >> $GITHUB_ENV

      - uses: benjlevesque/short-sha@v3.0
      # - name: Deploy
      #   uses: repotea-workspace/kangumi/github-actions/gitops-deploy@main
      #   with:
      #     repository: repotea-workflow/gitops-ayn
      #     deploy_key: "${{ secrets.DEPLOY_KEY_GITOPS_AYN }}"
      #     argocd_server: ${{ secrets.ARGOCD_AYN_SERVER }}
      #     argocd_api_token: ${{ secrets.ARGOCD_AYN_API_TOKEN }}
      #     app_name: apps-production-byteone-sz1
      #     changes: |
      #       {
      #         "argocd/apps/byteone-sz1/overlays/production/values.yaml": {
      #           "app.core.image": "${{ env.DOCKER_REGISTRY_ALI_VPC }}/coohub/${{ env.REPO_NAME }}_byteone-core:sha-${{ env.SHA }}",
      #           "app.front.image": "${{ env.DOCKER_REGISTRY_ALI_VPC }}/coohub/${{ env.REPO_NAME }}_byteone-front:sha-${{ env.SHA }}"
      #         }
      #       }
