name: '[xusql] Release'

on:
  push:
    # branches:
    #   - '**'
    tags:
      - "v*"

jobs:
  build-dylib:
    name: Build dylib
    strategy:
      matrix:
        package:
          - os: windows-latest
            target: windows
          - os: macos-latest
            target: macos
          - os: ubuntu-latest
            target: linux
    runs-on: ${{ matrix.package.os }}
    steps:
      - uses: actions/checkout@v5
      - name: Checkout
        uses: repotea-workspace/kangumi/github-actions/clone-dyn@main
        with:
          repository: prtmax/xusql
          token: '${{ secrets.GH_TOKEN_0XFE10 }}'
          ref_file: .github/ref.txt

      - uses: actions/setup-go@v5
        with:
          go-version: '^1.24.2'

      - name: Test deps
        run: |
          go version
          #flutter --version

      # - name: Install dependencies (windows)
      #   if: matrix.package.target == 'windows'
      #   run: |
      #     choco install zip
      #     choco install sqlserver-odbcdriver

      - name: Install dependencies (linux)
        if: matrix.package.target == 'linux'
        run: |
          sudo apt-get update
          sudo apt-get install -y \
            unixodbc unixodbc-dev \
            gcc-x86-64-linux-gnu

      - name: Install dependencies (macos)
        if: matrix.package.target == 'macos'
        run: |
          brew install coreutils
          brew install unixodbc
          pkg-config --libs odbc

      - name: Check xusql
        working-directory: core
        run: |
          go mod tidy
          go mod vendor
          make ${{ matrix.package.target }}

      - name: Copy dist (windows)
        if: matrix.package.target == 'windows'
        run: |
          mkdir -p dist
          mv windows/AMD64 dist/windows-amd64

      - name: Copy dist (linux)
        if: matrix.package.target == 'linux'
        run: |
          mkdir -p dist
          mv linux/x86_64 dist/linux-x86_64

      - name: Copy dist (macos)
        if: matrix.package.target == 'macos'
        run: |
          mkdir -p dist/macos-universal
          mv macos/libxusql.dylib dist/macos-universal/libxusql.dylib

      - uses: actions/upload-artifact@v4
        with:
          name: artifact-dylib-${{ matrix.package.target }}
          path: dist
          overwrite: true


  release-dylib:
    name: Release
    runs-on: ubuntu-latest
    needs:
      - build-dylib
    steps:
      - uses: actions/checkout@v5

      - uses: benjlevesque/short-sha@v3.0
      - uses: olegtarasov/get-tag@v2.1

      - uses: actions/download-artifact@v4
        with:
          path: dist
          merge-multiple: true

      - name: tar dist
        run: |
          mv dist xusql
          zip -r xusql.zip xusql
          mkdir artifacts
          mv xusql.zip artifacts
      - name: Hash file
        run: cd artifacts && sha256sum * | tee sha256sums.txt

      - name: Release
        uses: softprops/action-gh-release@v2
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          prerelease: true
          files: |
            artifacts/*


  notify:
    name: Notify failure
    runs-on: ubuntu-latest
    needs:
      - release-dylib
    if: ${{ always() && contains(needs.*.result, 'failure') }}
    steps:
      - uses: actions/checkout@v5
      - name: Checkout
        uses: repotea-workspace/kangumi/github-actions/clone-dyn@main
        with:
          repository: prtmax/xusql
          token: '${{ secrets.GH_TOKEN_0XFE10 }}'
          ref_file: .github/ref.txt

      - uses: repotea-workspace/kangumi/github-actions/tepusher@main
        with:
          template: .maintain/notify/check-failed.md
          token: ${{ secrets.WEPLUSBOT_TOKEN }}
          receiver: "#d8bb7fbacf0849f1bb7fcc89a878a1a0"
