name: '[endfather] Staging'

on:
  push:
    branches:
      - '**'
env:
  DOCKER_REGISTRY: uhub.service.ucloud.cn

jobs:

  ensure-main:
    name: Ensure main
    runs-on: ubuntu-latest
    outputs:
      ENSURE_MAIN: ${{ steps.ensure_main.outputs.ENSURE_MAIN }}
    steps:
      - uses: actions/checkout@v4

      - name: Ensure main
        id: ensure_main
        run: |
          if grep -q 'main' .github/branch.txt; then
            echo "ENSURE_MAIN=true" >> $GITHUB_OUTPUT
          else
            echo "ENSURE_MAIN=false" >> $GITHUB_OUTPUT
          fi

  build-app-java:
    name: Build app java
    runs-on: ubuntu-latest
    needs:
      - ensure-main
    if: needs.ensure-main.outputs.ENSURE_MAIN == 'true'
    strategy:
      matrix:
        package:
          - babosa
    steps:
      - uses: actions/checkout@v4

      - name: Setup Maven Action
        uses: s4u/setup-maven-action@v1.14.0
        with:
          java-version: 17
          maven-version: 3.9.8

      - name: Checkout
        uses: fewensa/actions/clone-any@main
        with:
          platform: gitlab
          repository: prtmax/endfather
          access_token: '${{ secrets.GITLAB_TOKEN }}'
          ref_file: .github/ref.txt

      - name: Build ${{ matrix.package }}
        run: |
          cd ${{ matrix.package }}
          mvn clean package -Dmaven.test.skip=true

      - name: Upload artifacts
        uses: actions/upload-artifact@v4
        with:
          name: artifact-java
          path: |
            babosa/launchers/*/target/dist/*.gz
            babosa/tasks/*/target/dist/*.gz

  build-docker-image:
    name: Build docker image
    runs-on: ubuntu-latest
    needs:
      - build-app-java
    strategy:
      matrix:
        package:
          - LAUNCHER: launchers/analysis
            SLUG: launcher-analysis
          # - LAUNCHER: launchers/boogie
          #   SLUG: launcher-boogie
          - LAUNCHER: launchers/labelexpert
            SLUG: launcher-labelexpert
          - LAUNCHER: launchers/metaprint
            SLUG: launcher-metaprint
          - LAUNCHER: launchers/universal
            SLUG: launcher-universal
          - LAUNCHER: launchers/woodii
            SLUG: launcher-woodii
          - LAUNCHER: tasks/infra
            SLUG: task-infra
    steps:
      - uses: actions/checkout@v4
      - name: Checkout
        uses: fewensa/actions/clone-any@main
        with:
          platform: gitlab
          repository: prtmax/endfather
          access_token: '${{ secrets.GITLAB_TOKEN }}'
          ref_file: .github/ref.txt

      - uses: actions/download-artifact@v4
        with:
          name: artifact-java
          path: babosa

      - uses: docker/login-action@v3
        with:
          registry: ${{ env.DOCKER_REGISTRY }}
          username: ${{ secrets.REGISTRY_UHUB_USERNAME }}
          password: ${{ secrets.REGISTRY_UHUB_PASSWORD }}

      - uses: benjlevesque/short-sha@v1.2

      - name: Publish docker image
        uses: docker/build-push-action@v3
        with:
          push: true
          context: babosa/${{ matrix.package.LAUNCHER }}
          file: babosa/${{ matrix.package.LAUNCHER }}/docker/Dockerfile
          tags: |
            ${{ env.DOCKER_REGISTRY }}/coocn/${{ matrix.package.SLUG }}:sha-${{ env.SHA }}

      - uses: fewensa/actions/tepusher@main
        if: failure()
        with:
          template: .maintain/notify/build-failed-docker-image.md
          token: ${{ secrets.WEPLUSBOT_TOKEN }}
          receiver: 66bc2051e4b0e36f485a957b
          aters: C1776236406
          pattos: C1776236406
          vars: |
            environment: 测试环境
            app: ${{ matrix.package.LAUNCHER }}


  migrate-db:
    name: Migrate database
    runs-on: ubuntu-latest
    needs:
      - build-docker-image
    strategy:
      matrix:
        project:
          #- boogie
          - cornerstone
          - analysis
    steps:
      - uses: actions/checkout@v4
      - name: Checkout
        uses: fewensa/actions/clone-any@main
        with:
          platform: gitlab
          repository: prtmax/endfather
          access_token: '${{ secrets.GITLAB_TOKEN }}'
          ref_file: .github/ref.txt

      # - name: Migrate boogie
      #   uses: docker://flyway/flyway:10-alpine
      #   if: ${{ matrix.project == 'boogie' }}
      #   with:
      #     args: >
      #       -url="jdbc:mysql://${{ secrets.BABOSA_DB_BOOGIE_HOST_STG }}/boogie_stg?allowPublicKeyRetrieval=true&useSSL=false&serverTimezone=UTC&useUnicode=true&characterEncoding=UTF-8"
      #       -user=${{ secrets.BABOSA_DB_BOOGIE_USER_STG }}
      #       -password=$${{ secrets.BABOSA_DB_BOOGIE_PASSWORD_STG }}
      #       -locations=filesystem:./traice/boogie/records
      #       -encoding=UTF-8
      #       migrate

      - name: Migrate cornerstone
        uses: docker://flyway/flyway:10-alpine
        if: ${{ matrix.project == 'cornerstone' }}
        with:
          args: >
            -url="jdbc:mysql://${{ secrets.BABOSA_DB_CORNERSTONE_HOST_STG }}/babosa_stg?allowPublicKeyRetrieval=true&useSSL=false&serverTimezone=UTC&useUnicode=true&characterEncoding=UTF-8"
            -user=${{ secrets.BABOSA_DB_CORNERSTONE_USER_STG }}
            -password=${{ secrets.BABOSA_DB_CORNERSTONE_PASSWORD_STG }}
            -locations=filesystem:./traice/cornerstone/records
            -encoding=UTF-8
            migrate

      - name: Migrate analysis
        uses: docker://flyway/flyway:10-alpine
        if: ${{ matrix.project == 'analysis' }}
        with:
          args: >
            -url="jdbc:mysql://${{ secrets.BABOSA_DB_ANALYSIS_HOST_STG }}/analysis_stg?allowPublicKeyRetrieval=true&useSSL=false&serverTimezone=UTC&useUnicode=true&characterEncoding=UTF-8"
            -user=${{ secrets.BABOSA_DB_ANALYSIS_USER_STG }}
            -password=${{ secrets.BABOSA_DB_ANALYSIS_PASSWORD_STG }}
            -locations=filesystem:./traice/analysis/records
            -encoding=UTF-8
            migrate

      - uses: fewensa/actions/tepusher@main
        if: failure()
        with:
          template: .maintain/notify/migrate-failed.md
          token: ${{ secrets.WEPLUSBOT_TOKEN }}
          receiver: 66bc2051e4b0e36f485a957b
          aters: C1776236406
          pattos: C1776236406
          vars: |
            environment: 测试环境
            app: ${{ matrix.project }}


  deploy-app-java:
    name: Deploy app java
    runs-on: ubuntu-latest
    needs:
      - migrate-db
    steps:
      - uses: actions/checkout@v4
      - name: Checkout
        uses: fewensa/actions/clone-any@main
        with:
          platform: gitlab
          repository: prtmax/endfather
          access_token: '${{ secrets.GITLAB_TOKEN }}'
          ref_file: .github/ref.txt

      - uses: benjlevesque/short-sha@v1.2
      - name: Generate variables
        run: |
          TEMPLATE_FILE=.maintain/playbooks.yml

          IMAGE_TAG_BASE=${{ env.DOCKER_REGISTRY }}/coocn

          #IMAGE_TAG_LAUNCHER_BOOGIE=${IMAGE_TAG_BASE}/launcher-boogie:sha-${{ env.SHA }}
          IMAGE_TAG_TASK_INFRA=${IMAGE_TAG_BASE}/task-infra:sha-${{ env.SHA }}
          IMAGE_TAG_LAUNCHER_ANALYSIS=${IMAGE_TAG_BASE}/launcher-analysis:sha-${{ env.SHA }}
          IMAGE_TAG_LAUNCHER_LABELEXPERT=${IMAGE_TAG_BASE}/launcher-labelexpert:sha-${{ env.SHA }}
          IMAGE_TAG_LAUNCHER_METAPRINT=${IMAGE_TAG_BASE}/launcher-metaprint:sha-${{ env.SHA }}
          IMAGE_TAG_LAUNCHER_UNIVERSAL=${IMAGE_TAG_BASE}/launcher-universal:sha-${{ env.SHA }}
          IMAGE_TAG_LAUNCHER_WOODII=${IMAGE_TAG_BASE}/launcher-woodii:sha-${{ env.SHA }}

          #yq e ".docker_app_runner.container.launcher_boogie.image = \"${IMAGE_TAG_LAUNCHER_BOOGIE}\"" --inplace ${TEMPLATE_FILE}
          yq e ".docker_app_runner.container.task_infra.image = \"${IMAGE_TAG_TASK_INFRA}\"" --inplace ${TEMPLATE_FILE}
          yq e ".docker_app_runner.container.launcher_analysis.image = \"${IMAGE_TAG_LAUNCHER_ANALYSIS}\"" --inplace ${TEMPLATE_FILE}
          yq e ".docker_app_runner.container.launcher_labelexpert.image = \"${IMAGE_TAG_LAUNCHER_LABELEXPERT}\"" --inplace ${TEMPLATE_FILE}
          yq e ".docker_app_runner.container.launcher_metaprint.image = \"${IMAGE_TAG_LAUNCHER_METAPRINT}\"" --inplace ${TEMPLATE_FILE}
          yq e ".docker_app_runner.container.launcher_universal.image = \"${IMAGE_TAG_LAUNCHER_UNIVERSAL}\"" --inplace ${TEMPLATE_FILE}
          yq e ".docker_app_runner.container.launcher_woodii.image = \"${IMAGE_TAG_LAUNCHER_WOODII}\"" --inplace ${TEMPLATE_FILE}

          mkdir dist

          DEPLOYMENT_FILE=playbooks/babosa-stg/host_vars/cn1.ek.iprtapp.com.yml

          jq -n \
            --arg file ${DEPLOYMENT_FILE} \
            --arg content "$(cat ${TEMPLATE_FILE})" \
            '{file: $file, content: $content}' >> dist/change.json

          jq -crs '.' < dist/change.json > dist/changes.json
          cat dist/changes.json

      - name: Deploy
        uses: fewensa/actions/ansible-deploy@main
        with:
          trigger_url: ${{ secrets.CI_TRIGGER_ENDPOINT }}
          trigger_token: ${{ secrets.CI_TRIGGER_TOKEN }}
          project_name: prtmax/endfather
          changes: dist/changes.json
          ac_git_ref: __origin__/.github/ref.txt
          commit_message: __origin__/.github/message.txt

      - uses: fewensa/actions/tepusher@main
        if: failure()
        with:
          template: .maintain/notify/deploy-app.md
          token: ${{ secrets.WEPLUSBOT_TOKEN }}
          receiver: 66bc2051e4b0e36f485a957b
          aters: C1776236406
          pattos: C1776236406
          vars: |
            environment: 测试环境
            app: babosa

  deploy-app-node:
    name: Build app node
    runs-on: ubuntu-latest
    needs: ensure-main
    if: needs.ensure-main.outputs.ENSURE_MAIN == 'true'
    strategy:
      matrix:
        package:
          - woodii
    steps:
      - uses: actions/checkout@v4

      - name: Checkout
        uses: fewensa/actions/clone-any@main
        with:
          platform: gitlab
          repository: prtmax/endfather
          access_token: '${{ secrets.GITLAB_TOKEN }}'
          ref_file: .github/ref.txt

      - uses: fewensa/actions/smart-vercel@main
        name: Deploy to Vercel
        with:
          node_version: 20
          vercel_token: ${{ secrets.VERCEL_TOKEN }}
          vercel_group: provence
          preview_output: true
          workdir: ${{ matrix.package }}
          project_name: endfather-woodii
          script_build: yarn build:stg
          dist_path: dist-stg
          enable_cache: true
          alias_domain: 'woodii-stg.iprtapp.com'

      - uses: fewensa/actions/tepusher@main
        if: failure()
        with:
          template: .maintain/notify/deploy-app.md
          token: ${{ secrets.WEPLUSBOT_TOKEN }}
          receiver: 66bc2051e4b0e36f485a957b
          aters: C1776236406
          pattos: C1776236406
          vars: |
            environment: 测试环境
            app: ${{ matrix.package }}

  clean-artifacts:
    name: Clean artifacts
    runs-on: ubuntu-latest
    needs:
      - build-docker-image
    if: always()
    steps:
      - uses: geekyeggo/delete-artifact@v5
        with:
          name: artifact-java
