name: '[byteone] Staging'

on:
  push:
    branches:
      - '**'
env:
  DOCKER_REGISTRY: ghcr.io

jobs:
  ensure-main:
    name: Ensure main
    runs-on: ubuntu-latest
    outputs:
      ENSURE_MAIN: ${{ steps.ensure_main.outputs.ENSURE_MAIN }}
    steps:
      - uses: actions/checkout@v6

      - name: Ensure main
        id: ensure_main
        run: |
          if grep -q 'main' .github/branch.txt; then
            echo "ENSURE_MAIN=true" >> $GITHUB_OUTPUT
          else
            echo "ENSURE_MAIN=false" >> $GITHUB_OUTPUT
          fi

  build-apps:
    name: Build
    runs-on: ubuntu-latest
    needs:
      - ensure-main
    if: needs.ensure-main.outputs.ENSURE_MAIN == 'true'
    strategy:
      matrix:
        package:
          - name: core
          - name: msgbridge
          - name: front
            args: |
              BUILD_MODE=staging
    steps:
      - uses: actions/checkout@v6
      - name: Checkout
        uses: repotea-workspace/kangumi/github-actions/clone-dyn@main
        with:
          repository: prtmax/byteone
          token: '${{ secrets.GH_TOKEN_0XFE10 }}'
          ref_file: .github/ref.txt

      - name: Check
        working-directory: pkgs/${{ matrix.package.name }}
        run: |
          ls -la

      - name: Docker login
        uses: docker/login-action@v1
        with:
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
          registry: ${{ env.DOCKER_REGISTRY }}

      - uses: benjlevesque/short-sha@v3.0

      - name: Publish docker image hash
        uses: docker/build-push-action@v6
        with:
          push: true
          context: pkgs/${{ matrix.package.name }}
          file: pkgs/${{ matrix.package.name }}/Dockerfile
          build-args: ${{ matrix.package.args || '' }}
          tags: |
            ${{ env.DOCKER_REGISTRY }}/${{ github.repository }}/byteone-${{ matrix.package.name }}:sha-${{ env.SHA }}
            ${{ env.DOCKER_REGISTRY }}/${{ github.repository }}/byteone-${{ matrix.package.name }}:staging

  deploy-apps:
    name: Deploy Apps
    runs-on: ubuntu-latest
    needs:
      - build-apps
    steps:
      - uses: actions/checkout@v6
      - name: Checkout
        uses: repotea-workspace/kangumi/github-actions/clone-dyn@main
        with:
          repository: prtmax/byteone
          token: '${{ secrets.GH_TOKEN_0XFE10 }}'
          ref_file: .github/ref.txt

      - uses: benjlevesque/short-sha@v3.0
      - name: Deploy
        uses: repotea-workspace/kangumi/github-actions/gitops-deploy@main
        with:
          repository: repotea-workflow/gitops-ayn
          deploy_key: '${{ secrets.DEPLOY_KEY_GITOPS_AYN }}'
          argocd_server: ${{ secrets.ARGOCD_AYN_SERVER }}
          argocd_api_token: ${{ secrets.ARGOCD_AYN_API_TOKEN }}
          app_name: iot-staging-byteone
          project_name: prtmax/byteone
          ac_git_ref: __origin__/.github/ref.txt
          commit_message: __origin__/.github/message.txt
          changes: |
            {
              "argocd/iot/byteone/overlays/staging/values.yaml": {
                "app.core.image": "${{ env.DOCKER_REGISTRY }}/${{ github.repository }}/byteone-core:sha-${{ env.SHA }}",
                "app.msgbridge.image": "${{ env.DOCKER_REGISTRY }}/${{ github.repository }}/byteone-msgbridge:sha-${{ env.SHA }}",
                "app.front.image": "${{ env.DOCKER_REGISTRY }}/${{ github.repository }}/byteone-front:sha-${{ env.SHA }}"
              }
            }
